# Generated by Django 5.0.6 on 2025-09-01 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('organisateur', models.CharField(blank=True, default='FASCH', max_length=255, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Le titre de l'article", max_length=200)),
                ('contenu', models.TextField(help_text="Le contenu de l'article")),
                ('auteur', models.CharField(default='FASCH', max_length=100)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, help_text="Image associée à l'article", null=True, upload_to='articles/')),
                ('est_active', models.BooleanField(default=True, help_text="Indique si l'article est actif ou non")),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AxeRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.CharField(choices=[('Preparatoire', 'Préparatoire'), ('Premiere Annee', 'Première Année'), ('Deuxieme Annee', 'Deuxième Année'), ('Troisieme Annee', 'Troisième Année'), ('Quatrieme Annee', 'Quatrième Année')], default='Preparatoire', max_length=50)),
                ('session', models.CharField(choices=[('session1', 'Session 1'), ('session2', 'Session 2')], default='session1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(error_messages={'unique': 'Cet email appartient déjà à une autre personne.'}, max_length=254, unique=True)),
                ('telephone', models.CharField(error_messages={'unique': 'Ce numero appartient déjà à une autre personne.'}, max_length=15, unique=True)),
                ('programme', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtapeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Intitulé de l'examen")),
                ('date', models.DateField(verbose_name="Date de l'examen")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('active', 'En cours'), ('upcoming', 'À venir')], default='upcoming', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('resume', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('doyen', 'Doyen'), ('vice_doyen_acad', 'Vice-Doyen Académique'), ('vice_doyen_admin', 'Vice-Doyen Administratif'), ('secretaire', 'Secrétaire Général'), ('agent_admin', 'Agent Administratif'), ('rap', 'Responsable Année Préparatoire'), ('chef_dept_socio', 'Chef de Département de Sociologie'), ('chef_dept_psy', 'Chef de Département de Psychologie'), ('chef_dept_com', 'Chef de Département de Communication Sociale'), ('chef_dept_ss', 'Chef de Département de Service Social')], max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Personnel administratif',
                'ordering': ['poste'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Cet email appartient déjà à un autre professeur.'}, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(error_messages={'unique': 'Ce numero appartient déjà à un autre professeur.'}, max_length=20, null=True, unique=True)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('Preparatoire', 'Préparatoire'), ('Premiere Annee', 'Première Année'), ('Deuxieme Annee', 'Deuxième Année'), ('Troisieme Annee', 'Troisième Année'), ('Quatrieme Annee', 'Quatrième Année')], default='Preparatoire', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteurs', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_publication', models.DateField()),
                ('domaines', models.CharField(blank=True, help_text='Séparer les domaines par des virgules', max_length=255)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Cet email appartient déjà à un autre étudiant.'}, max_length=254, unique=True)),
                ('telephone', models.CharField(error_messages={'unique': 'Ce numero appartient déjà à un autre étudiant.'}, max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.CharField(choices=[('Preparatoire', 'Préparatoire'), ('Premiere Annee', 'Première Année'), ('Deuxieme Annee', 'Deuxième Année'), ('Troisieme Annee', 'Troisième Année'), ('Quatrieme Annee', 'Quatrième Année')], default='Preparatoire', max_length=50)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestioncours.departement')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoraireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite_max', models.PositiveIntegerField(default=30)),
                ('est_ferme', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.cours')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.etudiant')),
                ('horaire_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.horairecours')),
            ],
            options={
                'unique_together': {('etudiant', 'horaire_cours')},
            },
        ),
    ]
