# Generated by Django 4.2.16 on 2025-04-16 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('organisateur', models.CharField(blank=True, default='FASCH', max_length=255, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Le titre de l'article", max_length=200)),
                ('contenu', models.TextField(help_text="Le contenu de l'article")),
                ('auteur', models.CharField(default='FASCH', max_length=100)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, help_text="Image associée à l'article", null=True, upload_to='articles/')),
                ('est_active', models.BooleanField(default=True, help_text="Indique si l'article est actif ou non")),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('programme', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('niveau', models.CharField(choices=[('Preparatoire', 'Préparatoire'), ('Premiere Annee', 'Première Année'), ('Deuxieme Annee', 'Deuxième Année'), ('Troisieme Annee', 'Troisième Année'), ('Quatrieme Annee', 'Quatrième Année')], default='Preparatoire', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HoraireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite_max', models.PositiveIntegerField(default=30)),
                ('est_ferme', models.BooleanField(default=False)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.cours')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.etudiant')),
                ('horaire_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.horairecours')),
            ],
            options={
                'unique_together': {('etudiant', 'horaire_cours')},
            },
        ),
    ]
