# Generated by Django 4.2.16 on 2025-04-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('Licence', 'Licence'), ('Maîtrise', 'Maîtrise')], max_length=100)),
            ],
        ),
    ]
