# Generated by Django 4.2.16 on 2025-04-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxeRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicationRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteurs', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_publication', models.DateField()),
                ('domaines', models.CharField(help_text='Séparer les domaines par des virgules', max_length=255)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
