# Generated by Django 4.2.16 on 2025-04-02 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_alter_etudiant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='organisateur',
            field=models.CharField(blank=True, default='FASCH', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(default='FASCH', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
