# Generated by Django 4.2.16 on 2025-04-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('doyen', 'Doyen'), ('vice_doyen_acad', 'Vice-Doyen Académique'), ('vice_doyen_admin', 'Vice-Doyen Administratif'), ('secretaire', 'Secrétaire Général'), ('agent_admin', 'Agent Administratif'), ('rap', 'Responsable Année Préparatoire'), ('chef_dept_socio', 'Chef de Département de Sociologie'), ('chef_dept_psy', 'Chef de Département de Psychologie'), ('chef_dept_com', 'Chef de Département de Communication Sociale'), ('chef_dept_ss', 'Chef de Département de Service Social')], max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Personnel administratif',
                'ordering': ['poste'],
            },
        ),
    ]
