# Generated by Django 4.2.16 on 2025-04-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
